### ISSUE TITLE
Tracking: Materialization synchronization improvements

### ISSUE THREAD

**Issue by esavier** [epiphany-platform/CommonDataLayer#620]
General task to track problems and fixes to materialization:
- [ ] DR transactions and triggers
- [ ] PUA data consistency 
- [ ] multi-PUA task synchronization

**Comment by Kononnable** [comment]
TODO: Validate/clarify before implementation
