### ISSUE TITLE
Add gRPC ingestion to CDL

### ISSUE THREAD

**Issue by luke-biel** [epiphany-platform/CommonDataLayer#68]
Messaging system located in utils/messaging_system is abstraction over Kafka and Rabbit, allowing it's clients to receive and produce messages from mentioned systems.
We have to add one more option - gRPC.

Ingestion layer must be able to switch between Kafka and gRPC using this system. This will require adjusting command-line parameters (in structopt).

DoD:
Whole retrieval layer (query-router, query-service) and schema registry is using gRPC through this abstraction.
Whole ingestion layer (data-router, command-service) can switch between gRPC and Kafka.

---

- [ ] Add gRPC to utils/messaging_system
- [ ] Switch query-service to MS
- [ ] Switch query-router to MS
- [ ] Switch schema-registry to MS
- [ ] Add gRPC as option to data-router
- [x] Add rabbit to data-router as option
- [ ] Add gRPC as option to command-service
- [x] Add rabbit to command-service as option

**Comment by luke-biel** [comment]
When starting with this task please discuss it with @Kononnable
